apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
  namespace: canary-demo

spec:
  replicas: 5

  strategy:
    canary:

      analysis:
        templates:
        - templateName: error-rate-check

      steps:
      - setWeight: 20
      - pause: {duration: 60s}

      - setWeight: 50
      - pause: {duration: 60s}

      - setWeight: 80
      - pause: {duration: 60s}

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"

    spec:
      containers:
      - name: myapp
        image: gauravgirase/canary:v1.0.0
        ports:
        - containerPort: 8080