apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: canary-demo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/GauravGirase/EKS-CANARY-DEPLOYMENT.git
    targetRevision: HEAD
    path: DEMO-2/apps/canary-demo

  destination:
    server: https://kubernetes.default.svc
    namespace: canary-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true